<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddWhatsappSupportSidebarmenu extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $whatsapp_supports = array(
            'whatsapp-support' => array(
                'module' => 'WhatsappSupport',
                'sidebar_menu' => 'whatsapp-support',
                'name' => 'WhatsApp Support',
                'lang_name' => 'whatsappsupport::whatsappsupport.whatsapp_support',
                'icon' => 'fab fa-whatsapp',
                'svg' => null,
                'route' => 'whatsapp-support',
                'parent_route' => null,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'position' => 19,
                'is_saas' => 0,
                'is_menu' => 1,
                'status' => 1,
                'menu_status' => 1,
                'relate_to_child' => 0,
                'alternate_module' => null,
                'permission_section' => 0,
                'user_id' => null,
                'type' => 1,
                'old_id' => null,
                'child' => array(
                    'settings' => array(
                        'module' => 'WhatsappSupport',
                        'sidebar_menu' => null,
                        'name' => 'Settings',
                        'lang_name' => 'whatsappsupport::whatsappsupport.settings',
                        'icon' => null,
                        'svg' => null,
                        'route' => 'whatsapp-support.settings',
                        'parent_route' => 'whatsapp-support',
                        'is_admin' => 1,
                        'is_teacher' => 0,
                        'is_student' => 0,
                        'is_parent' => 0,
                        'position' => 1,
                        'is_saas' => 0,
                        'is_menu' => 1,
                        'status' => 1,
                        'menu_status' => 1,
                        'relate_to_child' => 0,
                        'alternate_module' => null,
                        'permission_section' => 0,
                        'user_id' => null,
                        'type' => 2,
                        'old_id' => null,
                        'child' => array(
                            'update' => array(
                                'module' => null,
                                'sidebar_menu' => null,
                                'name' => 'Update',
                                'lang_name' => null,
                                'icon' => null,
                                'svg' => null,
                                'route' => 'whatsapp-support.settings.update',
                                'parent_route' => 'whatsapp-support.settings',
                                'is_admin' => 1,
                                'is_teacher' => 0,
                                'is_student' => 0,
                                'is_parent' => 0,
                                'position' => 1,
                                'is_saas' => 0,
                                'is_menu' => 0,
                                'status' => 1,
                                'menu_status' => 1,
                                'relate_to_child' => 0,
                                'alternate_module' => null,
                                'permission_section' => 0,
                                'user_id' => null,
                                'type' => 3,
                                'old_id' => null,
                            ),
                        ),
                    ),
                    'agents' => array(
                        'module' => 'WhatsappSupport',
                        'sidebar_menu' => null,
                        'name' => 'Agents',
                        'lang_name' => 'whatsappsupport::whatsappsupport.agents',
                        'icon' => null,
                        'svg' => null,
                        'route' => 'whatsapp-support.agents',
                        'parent_route' => 'whatsapp-support',
                        'is_admin' => 1,
                        'is_teacher' => 0,
                        'is_student' => 0,
                        'is_parent' => 0,
                        'position' => 2,
                        'is_saas' => 0,
                        'is_menu' => 1,
                        'status' => 1,
                        'menu_status' => 1,
                        'relate_to_child' => 0,
                        'alternate_module' => null,
                        'permission_section' => 0,
                        'user_id' => null,
                        'type' => 2,
                        'old_id' => null,
                        'child' => array(
                            'add' => array(
                                'module' => null,
                                'sidebar_menu' => null,
                                'name' => 'Add',
                                'lang_name' => null,
                                'icon' => null,
                                'svg' => null,
                                'route' => 'whatsapp-support.agents.store',
                                'parent_route' => 'whatsapp-support.agents',
                                'is_admin' => 1,
                                'is_teacher' => 0,
                                'is_student' => 0,
                                'is_parent' => 0,
                                'position' => 1,
                                'is_saas' => 0,
                                'is_menu' => 0,
                                'status' => 1,
                                'menu_status' => 1,
                                'relate_to_child' => 0,
                                'alternate_module' => null,
                                'permission_section' => 0,
                                'user_id' => null,
                                'type' => 3,
                                'old_id' => null,
                            ),
                            'update' => array(
                                'module' => null,
                                'sidebar_menu' => null,
                                'name' => 'Update',
                                'lang_name' => null,
                                'icon' => null,
                                'svg' => null,
                                'route' => 'whatsapp-support.agents.update',
                                'parent_route' => 'whatsapp-support.agents',
                                'is_admin' => 1,
                                'is_teacher' => 0,
                                'is_student' => 0,
                                'is_parent' => 0,
                                'position' => 2,
                                'is_saas' => 0,
                                'is_menu' => 0,
                                'status' => 1,
                                'menu_status' => 1,
                                'relate_to_child' => 0,
                                'alternate_module' => null,
                                'permission_section' => 0,
                                'user_id' => null,
                                'type' => 3,
                                'old_id' => null,
                            ),
                            'delete' => array(
                                'module' => null,
                                'sidebar_menu' => null,
                                'name' => 'Delete',
                                'lang_name' => null,
                                'icon' => null,
                                'svg' => null,
                                'route' => 'whatsapp-support.agents.delete',
                                'parent_route' => 'whatsapp-support.agents',
                                'is_admin' => 1,
                                'is_teacher' => 0,
                                'is_student' => 0,
                                'is_parent' => 0,
                                'position' => 3,
                                'is_saas' => 0,
                                'is_menu' => 0,
                                'status' => 1,
                                'menu_status' => 1,
                                'relate_to_child' => 0,
                                'alternate_module' => null,
                                'permission_section' => 0,
                                'user_id' => null,
                                'type' => 3,
                                'old_id' => null,
                            ),
                        ),
                    ),
                    'analytics' => array(
                        'module' => 'WhatsappSupport',
                        'sidebar_menu' => null,
                        'name' => 'Analytics',
                        'lang_name' => 'whatsappsupport::whatsappsupport.analytics',
                        'icon' => null,
                        'svg' => null,
                        'route' => 'whatsapp-support.analytics',
                        'parent_route' => 'whatsapp-support',
                        'is_admin' => 1,
                        'is_teacher' => 0,
                        'is_student' => 0,
                        'is_parent' => 0,
                        'position' => 3,
                        'is_saas' => 0,
                        'is_menu' => 1,
                        'status' => 1,
                        'menu_status' => 1,
                        'relate_to_child' => 0,
                        'alternate_module' => null,
                        'permission_section' => 0,
                        'user_id' => null,
                        'type' => 2,
                        'old_id' => null,
                    ),
                ),
            )
        );
        foreach ($whatsapp_supports as $data) {
            storePermissionData($data);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('', function (Blueprint $table) {
        });
    }
}
